#!/bin/bash
# Post-deploy wiring — run after `sam deploy` completes.
# Captures stack outputs, generates shared/config.js, syncs frontend to S3, and seeds DynamoDB.

set -e

STACK_NAME="${1:-hsg-hudoas-dev}"
AWSCLI="/c/Program Files/Amazon/AWSCLIV2/aws.exe"
PLATFORM_DIR="$(cd "$(dirname "$0")/../.." && pwd)"

export AWS_PROFILE=hsg-hudoas

echo "=== Capturing outputs from $STACK_NAME ==="
OUTPUTS=$("$AWSCLI" cloudformation describe-stacks --stack-name "$STACK_NAME" --query 'Stacks[0].Outputs' --output json)
echo "$OUTPUTS"

get_output() {
  echo "$OUTPUTS" | python -c "import sys,json; d={o['OutputKey']:o['OutputValue'] for o in json.load(sys.stdin)}; print(d.get('$1',''))"
}

API_ENDPOINT=$(get_output ApiEndpoint)
CLOUDFRONT_DOMAIN=$(get_output CloudFrontDomain)
USER_POOL_ID=$(get_output UserPoolId)
USER_POOL_CLIENT_ID=$(get_output UserPoolClientId)
DOCS_BUCKET=$(get_output DocsBucket)
STATIC_BUCKET=$(get_output StaticBucket)

echo ""
echo "ApiEndpoint:        $API_ENDPOINT"
echo "CloudFrontDomain:   $CLOUDFRONT_DOMAIN"
echo "UserPoolId:         $USER_POOL_ID"
echo "UserPoolClientId:   $USER_POOL_CLIENT_ID"
echo "DocsBucket:         $DOCS_BUCKET"
echo "StaticBucket:       $STATIC_BUCKET"

echo ""
echo "=== Writing frontend config ==="
cat > "$PLATFORM_DIR/shared/config.js" <<EOF
// Auto-generated by after-deploy.sh — do not edit by hand.
// Re-run the script after every stack update.
window.HSG_CONFIG = {
  apiBase: '${API_ENDPOINT}',
  userPoolId: '${USER_POOL_ID}',
  userPoolClientId: '${USER_POOL_CLIENT_ID}',
  region: 'us-east-1',
  cloudFrontDomain: '${CLOUDFRONT_DOMAIN}'
};
EOF
echo "Wrote $PLATFORM_DIR/shared/config.js"

echo ""
echo "=== Syncing frontend to S3 ($STATIC_BUCKET) ==="
"$AWSCLI" s3 sync "$PLATFORM_DIR" "s3://$STATIC_BUCKET/" \
  --exclude "backend/*" \
  --exclude "*.md" \
  --exclude ".git/*" \
  --exclude ".claude/*" \
  --exclude "node_modules/*" \
  --cache-control "public, max-age=300" \
  --delete

echo ""
echo "=== Seeding DynamoDB ==="
cd "$PLATFORM_DIR/backend"
node scripts/seed-dev.mjs

echo ""
echo "=== Done ==="
echo "Preview URL: https://$CLOUDFRONT_DOMAIN/"
echo ""
echo "Next: add a CNAME at your DNS provider:"
echo "  hudloansales  CNAME  $CLOUDFRONT_DOMAIN"
echo ""
echo "Then request an ACM cert in us-east-1:"
echo "  aws acm request-certificate --domain-name hudloansales.housestrategiesgroup.com --validation-method DNS --region us-east-1 --profile hsg-hudoas"
echo "  (The return ARN goes into sam deploy --parameter-overrides 'UseCustomDomain=true CertificateArn=<arn>')"
